site_name: Openveo Plugin Generator
repo_url: https://github.com/veo-labs/openveo-plugin-generator
theme: readthedocs
markdown_extensions:
  - fenced_code
  - tables
nav:
- 'INTRODUCTION': 'index.md'
- 'PLUGIN DEVELOPERS':
  - 'Prerequisites': 'prerequisites.md'
  - 'Getting started': 'getting-started.md'
  - 'Plugin structure': 'structure.md'
  - 'Plugin life cycle': 'plugin-life-cycle.md'
  - 'Hooks': 'hooks.md'
  - 'Template engine': 'template-engine.md'
  - 'Back end AngularJS': 'back-end.md'
  - 'Tutorial': 'tutorial.md'
  - 'conf.js': 'conf.md'
  - 'Logger': 'logger.md'
  - 'I18N and I10N': 'i18n.md'
  - 'CSS / SASS / JS compilation': 'compilation.md'
  - 'Coding standards': 'coding-standards.md'
  - 'Unit tests': 'unit-tests.md'
  - 'End to end tests': 'end-to-end-tests.md'
